language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer update --dev
  - pyrus channel-discover pear.phpunit.de
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash
  - mysql -e 'create database joomla_ut;'
  - mysql joomla_ut < Tests/Stubs/mysql.sql
  - psql -c 'create database joomla_ut;' -U postgres
  - psql -d joomla_ut -a -f Tests/Stubs/postgresql.sql

script:
  - phpunit
