<?php
/**
 * @copyright  Copyright (C) 2005 - 2013 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

use Joomla\Registry\AbstractRegistryFormat;

/**
 * Test class for Json.
 * Generated by PHPUnit on 2009-10-27 at 15:13:37.
 *
 * @since  1.0
 */
class FormatYamlTest extends PHPUnit_Framework_TestCase
{
	protected $fixture;

	public function setUp()
	{
		$this->fixture = AbstractRegistryFormat::getInstance('Yaml');
	}

	/**
	 * Test the objectToString method with an object as input.
	 *
	 * @return  void
	 *
	 * @since   1.0
	 */
	public function testObjectToStringWithObject()
	{
		$object = (object) array(
			'foo' => 'bar',
			'quoted' => '"stringwithquotes"',
			'booleantrue' => true,
			'booleanfalse' => false,
			'numericint' => 42,
			'numericfloat' => 3.1415,
			'section' => (object) array('key' => 'value'),
			'array' => (object) array('nestedarray' => (object) array('test1' => 'value1'))
		);

		$yaml =
'foo: bar
quoted: \'"stringwithquotes"\'
booleantrue: true
booleanfalse: false
numericint: 42
numericfloat: 3.1415
section:
    key: value
array:
    nestedarray: { test1: value1 }
';

		$this->assertEquals($this->fixture->objectToString($object), $yaml);
	}

	/**
	 * Test the objectToString method with an array as input.
	 *
	 * @return  void
	 *
	 * @since   1.0
	 */
	public function testObjectToStringWithArray()
	{
		$object = array(
			'foo' => 'bar',
			'quoted' => '"stringwithquotes"',
			'booleantrue' => true,
			'booleanfalse' => false,
			'numericint' => 42,
			'numericfloat' => 3.1415,
			'section' => array('key' => 'value'),
			'array' => array('nestedarray' => array('test1' => 'value1'))
		);

		$yaml =
'foo: bar
quoted: \'"stringwithquotes"\'
booleantrue: true
booleanfalse: false
numericint: 42
numericfloat: 3.1415
section:
    key: value
array:
    nestedarray: { test1: value1 }
';

		$this->assertEquals($this->fixture->objectToString($object), $yaml);
	}

	/**
	 * Test the stringToObject method.
	 *
	 * @return  void
	 *
	 * @since   1.0
	 */
	public function testStringToObject()
	{
		$object = (object) array(
			'foo' => 'bar',
			'quoted' => '"stringwithquotes"',
			'booleantrue' => true,
			'booleanfalse' => false,
			'numericint' => 42,
			'numericfloat' => 3.1415,
			'section' => (object) array('key' => 'value'),
			'array' => (object) array('nestedarray' => (object) array('test1' => 'value1'))
		);

		$yaml =
'foo: bar
quoted: \'"stringwithquotes"\'
booleantrue: true
booleanfalse: false
numericint: 42
numericfloat: 3.1415
section:
    key: value
array:
    nestedarray: { test1: value1 }
';
		$this->assertEquals($object, $this->fixture->stringToObject($yaml));
	}
}
